version: '3.1'

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    container_name: meu-db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: adminer

  app:
    build: ./flask
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: meu-app

